# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jupyter-spark-ws
#   namespace: bds
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 100Gi
#   storageClassName: pure-file

# ---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: jupyter-spark
  name: jupyter-spark
  namespace: bds
spec:
  ports:
    - port: 8888
  selector:
    app: jupyter-spark

---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-spark-headless
  namespace: bds
  labels:
    app: jupyter-spark
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: false
  selector:
    app: jupyter-spark
  ports:
  - name: blockmanager
    port: 7777
    protocol: TCP
  - name: driver
    port: 2222
    protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter-spark
  namespace: bds
spec:
  rules:
  - host: jupyter-spark.purestorage.int
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jupyter-spark
            port: 
              number: 8888

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-spark
  namespace: bds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-spark
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jupyter-spark
    spec:
      serviceAccountName: spark
      volumes:
        - name: dataset-vol
          hostPath:
            path: /fbd/deephub/datasets
        # - name: workspace-vol
        #   persistentVolumeClaim:
        #     claimName: yj-jupyter-ws
        - name: workspace-vol
          hostPath:
            path: /fbd/jupyter
      imagePullSecrets:
        - name: regcred
      containers:
      - name: jupyter-spark
        image: "harbor.purestorage.int/reddot/jupyterlab:3.6.6-pyspark-3.4.1"
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c
          - |
            jupyter serverextension enable --py jupyterlab_s3_browser && \
            jupyter lab --config='~/.jupyter/jupyter_notebook_config.json' \
            --notebook-dir='/ws/notebooks' \
            --LabApp.token='Flash4all!' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
        resources:
          requests:
            memory: "4G"
            cpu: 1
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: secret-key
        - name: S3_ENDPOINT
          value: 192.168.170.11
        - name: S3_USE_HTTPS
          value: "0"
        - name: JUPYTERLAB_S3_ENDPOINT
          value: http://192.168.170.11
        - name: JUPYTERLAB_S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: access-key
        - name: JUPYTERLAB_S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: secret-key
        volumeMounts:
          - name: dataset-vol
            mountPath: /dataset
          - name: workspace-vol
            mountPath: /ws
        ports:
          - name: blockmanager
            containerPort: 7777
            protocol: TCP
          - name: driver
            containerPort: 2222
            protocol: TCP