apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-tf-pv-ws
  namespace: bds
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fb-nfs3

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: jupyter-tf-pv
  name: jupyter-tf-pv
  namespace: bds
spec:
  ports:
    - port: 8888
  selector:
    app: jupyter-tf-pv

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter-tf-pv
  namespace: bds
spec:
  rules:
  - host: jupyter-tf-pv.purestorage.int
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jupyter-tf-pv
            port: 
              number: 8888

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bds
  name: jupyter-tf-pv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-tf-pv
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jupyter-tf-pv
    spec:
      volumes:
        - name: dataset-vol
          hostPath:
            path: /fbd/deephub/datasets
        - name: workspace-vol
          persistentVolumeClaim:
            claimName: jupyter-tf-pv-ws
      imagePullSecrets:
        - name: regcred
      containers:
      - name: jupyter-tf-pv
        image: "harbor.purestorage.int/reddot/tensorflow:22.08-tf2-py3"
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            jupyter serverextension enable --py jupyterlab_s3_browser && \
            jupyter lab --config='~/.jupyter/jupyter_notebook_config.json' \
            --notebook-dir='/ws/notebooks' \
            --LabApp.token='Flash4all!' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
        resources:
          requests:
            memory: "8G"
            cpu: 2
          # limits:
          #   nvidia.com/gpu: 1
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: secret-key
        - name: S3_ENDPOINT
          value: 192.168.170.11
        - name: S3_USE_HTTPS
          value: "0"
        - name: JUPYTERLAB_S3_ENDPOINT
          value: http://192.168.170.11
        - name: JUPYTERLAB_S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: access-key
        - name: JUPYTERLAB_S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: secret-key
        volumeMounts:
          - name: dataset-vol
            mountPath: /datasets
          - name: workspace-vol
            mountPath: /ws
