# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jupyter-pytorch-ws
#   namespace: bds
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Gi
#   storageClassName: fb-nfs3

# ---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: jupyter-pytorch
  name: jupyter-pytorch
  namespace: bds
spec:
  ports:
    - port: 8888
  selector:
    app: jupyter-pytorch

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter-pytorch
  namespace: bds
spec:
  rules:
  - host: jupyter-pytorch.purestorage.int
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jupyter-pytorch
            port: 
              number: 8888

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bds
  name: jupyter-pytorch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-pytorch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jupyter-pytorch
    spec:
      volumes:
        - name: dataset-vol
          hostPath:
            path: /fbd/deephub/datasets
        # - name: workspace-vol
        #   persistentVolumeClaim:
        #     claimName: jupyter-pytorch-ws
        - name: workspace-vol
          hostPath:
            path: /fbd/jupyter
        - name: model-vol
          hostPath:
            path: /fbd/deephub/models
      imagePullSecrets:
        - name: regcred
      containers:
      - name: jupyter-pytorch
        image: "harbor.purestorage.int/reddot/pytorch:23.10-py3"
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c
          - |
            jupyter serverextension enable --py jupyterlab_s3_browser && \
            jupyter lab --config='~/.jupyter/jupyter_notebook_config.json' \
            --notebook-dir='/ws/notebooks' \
            --LabApp.token='Flash4all!' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
        resources:
          requests:
            memory: "32G"
            cpu: 8
          limits:
            nvidia.com/gpu: 2
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: secret-key
        - name: S3_ENDPOINT
          value: 192.168.170.11
        - name: S3_USE_HTTPS
          value: "0"
        - name: JUPYTERLAB_S3_ENDPOINT
          value: http://192.168.170.11
        - name: JUPYTERLAB_S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: access-key
        - name: JUPYTERLAB_S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: bds-s3
              key: secret-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-yijiang
              key: api-key
        volumeMounts:
          - name: dataset-vol
            mountPath: /datasets
          - name: model-vol
            mountPath: /models
          - name: workspace-vol
            mountPath: /ws
