apiVersion: v1
kind: Pod
metadata:
  name: kaniko-tf2
spec:
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args: 
        - "--context=s3://yifeng/kaniko/build.tar.gz"
        - "--destination=harbor.purestorage.int/reddot/tensorflow:23.05-tf2-py3"
        - "--dockerfile=build/tf2.Dockerfile"
        - "--skip-tls-verify"
        - "--cache=true"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: yifeng-s3
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: yifeng-s3
              key: secret-key
        - name: AWS_REGION
          value: local
        - name: S3_ENDPOINT
          value: http://192.168.170.22
        - name: S3_FORCE_PATH_STYLE
          value: "true"
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
  restartPolicy: Never
